stages:
  prepare_data:
    cmd: Rscript src/prepare_data.R
    deps:
    - data/lego-minifigures-classification
    - src/prepare_data.R
    params:
    - prepare_data
    outs:
    - data/prepared/test
    - data/prepared/train
  train:
    cmd: Rscript src/train.R
    deps:
    - data/prepared/train
    - src/train.R
    params:
    - train
    outs:
    - data/model
  evaluate:
    cmd: Rscript src/evaluate.R
    deps:
    - data/model
    - data/prepared/test
    - src/evaluate.R
    params:
    - evaluate
    outs:
    - confusion_matrix.png
    metrics:
    - metrics.json
  load_data:
    cmd: Rscript src/load_data.R
    outs:
    - data/lego-minifigures-classification
    deps:
    - src/load_data.R
