prepare_data:
  input: data/lego-minifigures-classification
  train_output: data/prepared/train
  test_output: data/prepared/test

train:
  input: data/prepared/train
  model: data/model
  batch_size: 17
  num_epochs: 2

evaluate:
  test_dataset: data/prepared/test
  model: data/model
  metrics: metrics.json
  confusion_matrix: confusion_matrix.png
