name: model-training
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    container:
      image: docker://geraudster/lego-mlops-runner:latest
      options: -v /home/geraud/lego-mlops-cache:/home/geraud/lego-mlops-cache:rw
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          Rscript -e "install.packages('renv'); renv::init(); renv::restore(); torch::install_torch()"
          pipenv --python 3.8 sync
          pipenv run dvc pull --run-cache
          pipenv run dvc repro

          echo '## Metrics' >> report.md
          pipenv run dvc metrics diff main --show-md >> report.md
          echo '## Params' >> report.md
          pipenv run dvc params diff main --show-md >> report.md
          echo '## Confusion matrix' >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md
